# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f9d6cf94e4ee278de699a2e6a8701eeddb04f8cdb40a67c4e19426eaf3dd604726fb388985a70cb0a208de064a442b4d9ee83825f27b9aa8155423c969dfaf6

test:
  secret_key_base: f05b3668ac5b5c8575340404852e6e59d2b17b82db98346ac617547e9629b82d046dffb4bb0f03da439bcadb8442d77e88486242c3291fb559076e09bb77cdef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
